Piece together multi-message responses
RedHatInsights/receptor_controller-client-ruby pull request #22
Opened 2020-08-04 16:04 UTC by lindgrenj6

2020-08-04 18:04 UTC, slemrmartin requested changes
As I would like to keep blocking directives for simple requests, not sure if it's worth doing this PR. It'll need changes to do it in a generic way.

One argument is, that now we're using blocking requests either for POST or for GET one record (not lists) so more responses of type "response" won't come. 

The second argument is, that there is +1 JSON parse and convert for each request

2020-08-04 18:04 UTC, slemrmartin commented on lib/receptor_controller/client/directive_blocking.rb
> +    def response_success(msg_id, message_type, serial, response)
@lindgrenj6 the same methods (success, error etc.) are in directive_non_blocking.rb, need to be changed in the same way

2020-08-04 18:04 UTC, slemrmartin commented on lib/receptor_controller/client/directive_blocking.rb
> +        acc["count"].nil? ? acc["count"] = pages[num][:body]["count"] : acc["count"] += pages[num][:body]["count"]
it shouldn't be expected the body is coming from Ansible Tower, this is common gem (at least it's used for satellite check now). 
Moreover "count" is there only if there is successful response

2020-08-04 18:04 UTC, slemrmartin commented on lib/receptor_controller/client/directive_blocking.rb
> +        next(pages[num]) unless pages[num][:body].key?("results")
body can be also string in case of error returned by receptor node

2020-08-12 19:46 UTC, syncrou commented
@lindgrenj6 is this still needed? I see a conflict as well.

2020-08-13 15:29 UTC, lindgrenj6 commented
@syncrou we'll probably need to do something like this eventually - but it should be done in a generic way for both directive blocking/non-blocking. We also need to brainstorm a bit to see if we can come up with a way to not have to parse the json every time. 

Closing for now since we have other (bigger) problems to work on.

2020-08-13 15:29 UTC, closed without merging